# Generated by Django 4.2.9 on 2024-05-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_username_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
                ('user_otp', models.CharField(max_length=6)),
            ],
        ),
    ]
