# Generated by Django 4.2.9 on 2024-05-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
