# Generated by Django 4.2.9 on 2024-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('user_name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('user_otp', models.CharField(max_length=7)),
            ],
        ),
    ]
