# Generated by Django 4.2.9 on 2024-05-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='user_name',
            new_name='user_email',
        ),
    ]
